services:
  ren:
    build:
      context: .
    restart: unless-stopped
    networks:
      - ren-network
    volumes:
      - type: bind
        source: ./data/ren
        target: /data
    environment:
      - TOKEN=${TOKEN}
      - PREFIX=${PREFIX}
      - TZ=${TIMEZONE:-America/Vancouver}
      - PUID=1000
      - CUSTOM_REDBOT_PACKAGE=git+https://github.com/SFUAnime/Ren.git@V3/testing
      - EXTRA_ARGS=${EXTRA_ARGS}
networks:
  ren-network:
    driver: bridge
